import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Calendar,
  Clock,
  BarChart,
  Map,
  FileX,
  AlignJustify,
  MapPin,
  Menu,
  Phone,
  Mail,
  CheckCircle2,
  Home,
  Tv,
  Tv2,
  Router,
  Camera,
  Bell,
  Lightbulb,
  SpeakerHigh,
  Plug,
  Search,
  SquareArrowOutUpRight,
  ArrowUpRight
} from "lucide-react"

export type Icon = React.ComponentType<React.SVGProps<SVGSVGElement>>

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  calendar: Calendar,
  check: Check,
  time: Clock,
  analytics: BarChart,
  map: Map,
  fileX: FileX,
  twitter: Twitter,
  menu: AlignJustify,
  hamburger: Menu,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  checkCircle: CheckCircle2,
  home: Home,

  // TV and Smart Home Icons
  tv: Tv,
  tvMount: Tv2,
  tvUnmount: SquareArrowOutUpRight,
  tvRemount: ArrowUpRight,
  outlet: Plug,
  smartHome: Router,
  camera: Camera,
  doorbell: Bell,
  lighting: Lightbulb,
  speaker: SpeakerHigh,
  search: Search
}