import {
  ArrowRight,
  Calendar,
  CheckCircle,
  Clock,
  Download,
  Home,
  Mail,
  MapPin,
  Phone,
  Plus,
  Star,
  Tv,
  MonitorX,
  User,
  Wifi,
  X,
  Image,
  Camera,
  Shield,
  Lightbulb,
  ChevronDown,
  ChevronUp,
  Loader2,
  Eye,
  EyeOff,
  Lock,
  Check,
  Copy,
  Edit,
  Trash2,
  Settings,
  Users,
  TrendingUp,
  Activity,
  CreditCard,
  Bell,
  Filter,
  RotateCcw,
  RefreshCw,
  AlertTriangle,
  Info,
  Package,
  FileText,
  Send,
  UserPlus,
  LogOut,
  Menu,
  Search,
  SlidersHorizontal,
  BarChart3,
  PieChart,
  DollarSign,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  MapPin as MapPinIcon,
  Phone as PhoneIcon,
  Mail as MailIcon,
  CheckCircle2,
  XCircle,
  AlertCircle,
  Zap,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";

export const Icons = {
  arrowRight: ArrowRight,
  calendar: Calendar,
  checkCircle: CheckCircle,
  clock: Clock,
  download: Download,
  home: Home,
  mail: Mail,
  mapPin: MapPin,
  phone: Phone,
  plus: Plus,
  star: Star,
  tv: Tv,
  tvUnmount: MonitorX,
  smartHome: Home,
  user: User,
  wifi: Wifi,
  x: X,
  image: Image,
  camera: Camera,
  shield: Shield,
  lightbulb: Lightbulb,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  loader2: Loader2,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  check: Check,
  copy: Copy,
  edit: Edit,
  trash2: Trash2,
  settings: Settings,
  users: Users,
  trendingUp: TrendingUp,
  activity: Activity,
  creditCard: CreditCard,
  bell: Bell,
  filter: Filter,
  rotateCcw: RotateCcw,
  refreshCw: RefreshCw,
  alertTriangle: AlertTriangle,
  info: Info,
  package: Package,
  fileText: FileText,
  send: Send,
  userPlus: UserPlus,
  logOut: LogOut,
  menu: Menu,
  search: Search,
  slidersHorizontal: SlidersHorizontal,
  barChart3: BarChart3,
  pieChart: PieChart,
  dollarSign: DollarSign,
  calendarIcon: CalendarIcon,
  clockIcon: ClockIcon,
  mapPinIcon: MapPinIcon,
  phoneIcon: PhoneIcon,
  mailIcon: MailIcon,
  checkCircle2: CheckCircle2,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  zap: Zap,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
};